site_name: ForgeGradle文档
#theme:

site_description: The Chinese translation of ForgeGradle Documentation
repo_url: https://github.com/Meow-J/ForgeGradle-Documentation-CN

pages:
- ['../README.md', '主页']
- ['index.md', '介绍']
- ['cookbook.md', '食谱']
- ['user-guide/shading.md', '用户指南', 'Shading']
- ['reference/mcblock.md', '进阶参考', "Minecraft{}"]
- ['reference/tasks.md', '进阶参考', "任务"]

markdown_extensions:
  - admonition
  
extra_css:
  - css/code.css
