site_name: ForgeGradle文档
#theme:

site_description: The Chinese translation of ForgeGradle Documentation
repo_url: https://github.com/Meow-J/ForgeGradle-Documentation-CN

pages:
  - 主页: 'index.md'
  - ['index.md', '介绍']
  - ['cookbook.md', '配方']
  - ['user-guide/shading.md', 'User Guide', '包含外部库到Jar中(Shading)']
  - ['reference/mcblock.md', 'Adept Reference', "Minecraft{}"]
  - ['reference/tasks.md', 'Adept Reference', "任务"]
